server:
  port: ${SERVER_PORT}

spring:
  application:
    name: reactive-rating-service
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      schema: reactive_rating_service

client:
  reactive-product-service:
    baseUrl: ${REACTIVE_PRODUCT_SERVICE_URL}
    timeout: ${REACTIVE_PRODUCT_SERVICE_TIMEOUT}
    numRetries: ${REACTIVE_PRODUCT_SERVICE_RETRIES_NUMBER}